package com.example.ui.localization

/**
 * Multilingual UI localization strings for HABEEB LF TRACK.
 * Supports English, Hausa, and Arabic for core interface navigation,
 * actions, settings, theme switching, prayer alarm controls, and financial wallet,
 * while preserving sacred Quranic Arabic text.
 */
object AppStrings {

  data class Translation(
    val appTitle: String,
    val tabStudy: String,
    val tabDeen: String,
    val tabAi: String,
    val tabWallet: String,
    val tabPlanner: String,
    val welcomePrefix: String,
    val dashboardOverview: String,
    val nextPrayer: String,
    val prayerRing: String,
    val alarmActive: String,
    val silentMode: String,
    val studyStreak: String,
    val tasksDone: String,
    val priorityTasks: String,
    val myFiles: String,
    val settings: String,
    val signOut: String,
    val cancel: String,
    val save: String,
    val add: String,
    val delete: String,
    val edit: String,
    val addIncome: String,
    val addExpense: String,
    val addSavings: String,
    val availableBalance: String,
    val monthlyIncome: String,
    val monthlyExpenses: String,
    val totalSavings: String,
    val halalBudget: String,
    val addTimetable: String,
    val uploadFile: String,
    val searchPlaceholder: String,
    val themeMode: String,
    val system: String,
    val lightMode: String,
    val darkMode: String,
    val language: String,
    val selectLanguage: String,
    val filterAll: String,
    val filterIncome: String,
    val filterExpenses: String,
    val filterSavings: String,
    val filterSadaqah: String,
    val sadaqahGiven: String,
    val editTransaction: String,
    val deleteConfirmTitle: String,
    val deleteConfirmMessage: String,
    val amount: String,
    val description: String,
    val category: String,
    val optionalNote: String,
    val date: String,
    val invalidAmountError: String,
    val titleRequiredError: String,
    val testAdhanAlarm: String,
    val stopSound: String,
    val masterAlarm: String,
    val masterAlarmSub: String
  )

  private val english = Translation(
    appTitle = "HABEEB LF TRACK",
    tabStudy = "Study",
    tabDeen = "Deen",
    tabAi = "Habeeb AI",
    tabWallet = "Wallet",
    tabPlanner = "Planner",
    welcomePrefix = "You are welcome",
    dashboardOverview = "Dashboard Overview",
    nextPrayer = "Next Prayer",
    prayerRing = "Prayer Ring 🔔",
    alarmActive = "Alarm Active 🚨",
    silentMode = "Silent Mode 🔕",
    studyStreak = "Study Streak",
    tasksDone = "Tasks Done",
    priorityTasks = "Priority Tasks",
    myFiles = "My Files",
    settings = "Settings",
    signOut = "Sign Out",
    cancel = "Cancel",
    save = "Save",
    add = "Add",
    delete = "Delete",
    edit = "Edit",
    addIncome = "+ Income",
    addExpense = "- Expense",
    addSavings = "💎 Savings",
    availableBalance = "TOTAL AVAILABLE BALANCE",
    monthlyIncome = "Monthly Income",
    monthlyExpenses = "Monthly Expenses",
    totalSavings = "Total Savings",
    halalBudget = "Halal Budget",
    addTimetable = "Add Timetable Block",
    uploadFile = "Upload File",
    searchPlaceholder = "Search...",
    themeMode = "Theme Mode",
    system = "System",
    lightMode = "☀️ Light",
    darkMode = "🌙 Dark",
    language = "Language",
    selectLanguage = "Select Language",
    filterAll = "All",
    filterIncome = "Income",
    filterExpenses = "Expenses",
    filterSavings = "Savings",
    filterSadaqah = "Sadaqah",
    sadaqahGiven = "Sadaqah Given This Month",
    editTransaction = "Edit Transaction",
    deleteConfirmTitle = "Delete Transaction",
    deleteConfirmMessage = "Are you sure you want to delete this transaction?",
    amount = "Amount ($)",
    description = "Description / Title",
    category = "Category",
    optionalNote = "Optional Note / Reason",
    date = "Date",
    invalidAmountError = "Please enter a valid amount greater than 0",
    titleRequiredError = "Please enter a description or title",
    testAdhanAlarm = "Test Adhan Alarm 🚨",
    stopSound = "Stop Sound ⏹️",
    masterAlarm = "Master Prayer Alarm 🚨",
    masterAlarmSub = "Play Adhan audio & send notifications"
  )

  private val hausa = Translation(
    appTitle = "HABEEB LF TRACK",
    tabStudy = "Karatu",
    tabDeen = "Addini",
    tabAi = "Habeeb AI",
    tabWallet = "Asusu",
    tabPlanner = "Jadawali",
    welcomePrefix = "Barka da zuwa",
    dashboardOverview = "Bayanin Farko",
    nextPrayer = "Sallah ta Gaba",
    prayerRing = "Zoben Sallah 🔔",
    alarmActive = "Ƙararrawar Sallah 🚨",
    silentMode = "Yanayin Shuru 🔕",
    studyStreak = "Kwanakin Karatu",
    tasksDone = "Ayyukan da aka gama",
    priorityTasks = "Muhimman Ayyuka",
    myFiles = "Fayiloli Na",
    settings = "Saituna",
    signOut = "Fita",
    cancel = "Soke",
    save = "Ajiye",
    add = "Ƙara",
    delete = "Goge",
    edit = "Gyara",
    addIncome = "+ Kudin Shiga",
    addExpense = "- Kudin Fita",
    addSavings = "💎 Ajiya",
    availableBalance = "JIMILLAR KUƊIN DAKE AKWAI",
    monthlyIncome = "Kudin Shiga na Wata",
    monthlyExpenses = "Kudin Fita na Wata",
    totalSavings = "Jimillar Ajiya",
    halalBudget = "Kasafin Halal",
    addTimetable = "Ƙara Jadawalin Karatu",
    uploadFile = "Ɗora Fayil",
    searchPlaceholder = "Bincika...",
    themeMode = "Yanayin Bayyanar App",
    system = "Na Na'ura",
    lightMode = "☀️ Haske",
    darkMode = "🌙 Duhu",
    language = "Harshe",
    selectLanguage = "Zaɓi Harshe",
    filterAll = "Duka",
    filterIncome = "Kudin Shiga",
    filterExpenses = "Kudin Fita",
    filterSavings = "Ajiya",
    filterSadaqah = "Sadaka",
    sadaqahGiven = "Sadakar da aka bayar a wannan watan",
    editTransaction = "Gyara Bayanin Kuɗi",
    deleteConfirmTitle = "Goge Wannan Bayani",
    deleteConfirmMessage = "Shin ka tabbata kana son goge wannan bayanin kuɗin?",
    amount = "Adadin Kuɗi ($)",
    description = "Bayanin Abin da aka yi da kuɗin",
    category = "Rukuni",
    optionalNote = "Ƙarin Bayani (Idan akwai)",
    date = "Rana",
    invalidAmountError = "Da fatan za a shigar da adadin kuɗi mai ma'ana sama da 0",
    titleRequiredError = "Da fatan za a rubuta bayanin abin",
    testAdhanAlarm = "Gwada Ƙararrawar Kiran Sallah 🚨",
    stopSound = "Dakata da Sautin ⏹️",
    masterAlarm = "Babban Ƙararrawar Sallah 🚨",
    masterAlarmSub = "Kira sallah tare da aiko da sanarwa"
  )

  private val arabic = Translation(
    appTitle = "HABEEB LF TRACK",
    tabStudy = "الدراسة",
    tabDeen = "الدين",
    tabAi = "حبيب AI",
    tabWallet = "المحفظة",
    tabPlanner = "المخطط",
    welcomePrefix = "أهلاً بك",
    dashboardOverview = "لوحة التحكم",
    nextPrayer = "الصلاة القادمة",
    prayerRing = "حلقة الصلاة 🔔",
    alarmActive = "المنبه مفعّل 🚨",
    silentMode = "الوضع الصامت 🔕",
    studyStreak = "أيام الدراسة المتتالية",
    tasksDone = "المهام المنجزة",
    priorityTasks = "المهام ذات الأولوية",
    myFiles = "ملفاتي",
    settings = "الإعدادات",
    signOut = "تسجيل الخروج",
    cancel = "إلغاء",
    save = "حفظ",
    add = "إضافة",
    delete = "حذف",
    edit = "تعديل",
    addIncome = "+ دخل",
    addExpense = "- مصروف",
    addSavings = "💎 ادخار",
    availableBalance = "إجمالي الرصيد المتاح",
    monthlyIncome = "الدخل الشهري",
    monthlyExpenses = "المصروف الشهري",
    totalSavings = "إجمالي المدخرات",
    halalBudget = "ميزانية حلال",
    addTimetable = "إضافة فترة جدول",
    uploadFile = "رفع ملف",
    searchPlaceholder = "بحث...",
    themeMode = "وضع المظهر",
    system = "النظام",
    lightMode = "☀️ نهاري",
    darkMode = "🌙 ليلي",
    language = "اللغة",
    selectLanguage = "اختر اللغة",
    filterAll = "الكل",
    filterIncome = "الدخل",
    filterExpenses = "المصروفات",
    filterSavings = "المدخرات",
    filterSadaqah = "الصدقات",
    sadaqahGiven = "الصدقات المخرجة هذا الشهر",
    editTransaction = "تعديل المعاملة",
    deleteConfirmTitle = "حذف المعاملة",
    deleteConfirmMessage = "هل أنت متأكد من رغبتك في حذف هذه المعاملة؟",
    amount = "المبلغ ($)",
    description = "الوصف / العنوان",
    category = "الفئة",
    optionalNote = "ملاحظة إضافية",
    date = "التاريخ",
    invalidAmountError = "يرجى إدخال مبلغ صحيح أكبر من 0",
    titleRequiredError = "يرجى كتابة عنوان أو وصف للمعاملة",
    testAdhanAlarm = "تجربة منبه الأذان 🚨",
    stopSound = "إيقاف الصوت ⏹️",
    masterAlarm = "المنبه الرئيسي للصلوات 🚨",
    masterAlarmSub = "تشغيل صوت الأذان وإرسال الإشعارات"
  )

  fun get(language: String): Translation {
    return when {
      language.startsWith("Hausa", ignoreCase = true) -> hausa
      language.startsWith("Arabic", ignoreCase = true) || language.contains("العربية") -> arabic
      else -> english
    }
  }
}
